create loan
xpntek/bookstore-api pull request #4
Opened 2023-03-13 10:01 UTC by elton971

2023-03-17 00:28 UTC, FranciscoUqueio requested changes

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Authors/AuthorSpecification/FoundAuthorByFullNameSpecification.cs
se na base de dados tiver "Mia Couto" e o utilizador introduzir "mia couto" nao irá encontrar

2023-03-17 00:28 UTC, FranciscoUqueio commented on API/Controllers/AuthorsController.cs
os endpoints devem retornar Task<IActionResult>

2023-03-17 00:28 UTC, FranciscoUqueio commented on API/Controllers/BooksController.cs
os endpoints devem retornar Task<IActionResult>

2023-03-17 00:28 UTC, FranciscoUqueio commented on API/Controllers/CategoriesController.cs
os endpoints devem retornar Task <IActionResult>

2023-03-17 00:28 UTC, FranciscoUqueio commented on API/Controllers/FavoritesController.cs
os endpoints devem retornar Task<IActionResult>

2023-03-17 00:28 UTC, FranciscoUqueio commented on API/Controllers/LoansController.cs
os endpoints devem retornar Task<IActionResult>

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Dtos/AuthorDto.cs
Falta mapear o ID

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Dtos/BookDto.cs
Falta mapear o ID

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Dtos/CategoryDto.cs
Falta mapear o ID

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Dtos/FavoriteDto.cs
Falta mapear o ID

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Dtos/LoanDto.cs
Falta mapear o ID

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Authors/CreateAuthors.cs
rever nomenclatura da classe
apenas um author será criado

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Authors/CreateAuthors.cs
> +        private readonly DataContext _context;
qual é a necessidade do Datacontext

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Books/BookSpecification/FoundBookAuthorByBookIdSpecification.cs
> +namespace Application.Features.Books.BookSpecification;
alterar o nome da pasta de specification para "Specifications"

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Books/BookSpecification/FoundBookByISBNSpecification.cs
na verificacao se tiver um ISBN "1abcd" e o utilizador enviar o ISBN "1abcD" nao irá encontrar

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Books/CreateBookAuthor.cs
> +                return Results.InternalError("The book don't have author");
rever o tipo de erro

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Books/CreateBookAuthor.cs
> +                var bookAuthDto = new BookDto()
a forma de preencher o dto nao é aconselhavel. utilize o objecto que foi criado

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Books/CreateBookAuthor.cs
> +                var bookAuthorsList = new List<BookAuthor>();
variavel nao util no codigo

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Books/CreateBookAuthor.cs
rever nomenclatura da classe

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Books/DeleteBookAuthors.cs
rever nomenclatura da classe

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Books/DeleteBookAuthors.cs
> +                var bookSpec = new FoundBookByISBNSpecification(bookObject.ISBN);
porquê pesquisar pelo objecto utilizando o ISBN? porque nao utilizar o ID?
principalmente por estar a pesquisar na tabela associativa

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Books/DeleteBookAuthors.cs
> +                _unitOfWork.Repository<BookAuthor>().Delete(bookAuthor);
se o livro tiver multiplos autores irá dar erro

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Books/ListBookById.cs
rever nomenclatura da classe

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Books/ListBooksAuthors.cs
rever nomenclatura da classe

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Books/UpdateBookAuthor.cs
> +                return Results.InternalError("The book don't have author");
rever o tipo de erro

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Books/UpdateBookAuthor.cs
> +                var bookAuthDto = new BookDto()
utilize o objecto actualizado para criar a dto

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Books/UpdateBookAuthor.cs
> +                var bookAuthorsList = new List<BookAuthor>();
variavel sem utilidade

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Categories/ListCategoryById.cs
rever nomenclatura da classe

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Categories/Specification/FoundCategoryByDescriptionSpecification.cs
se na bd existir a categoria "accao" e o utilizador introduzir "Accao", nao irá encontrar

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Favorites/CreateFavorite.cs
> +            if (client is  null)
só em um caso muito milagroso é que esta validacao será true

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Favorites/CreateFavorite.cs
> +                UserId = _userAccessor.GetCurrentUserID()
o favorito nao pode ser a associacao de um Book e um AplicationUser
tem que ser a associacao de um Book e um Client

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Favorites/Specification/FoundClientByIdSpecification.cs
1. se o specification mexe a entidade client, entao deve estar na pasta de specifications do client
2. a pesquisa de um client deve ser utilizando o ID do client

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Favorites/Specification/ListFavoriteSpecification.cs
rever o nome da classe

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Loans/CreateLoan.cs
> +                return Results.InternalError(" The user must make one loan ");
rever o tipo de erro

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Loans/CreateLoan.cs
> +            var newLoan = new Loan()
1. a multa nao pode ser algo que se possa introduzir
2. a data de retorno deve ser colocada no acto de retorno, e nao no acto de emprestimo. Deve haver um endpoint para fazer a devolucao de um livro

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Loans/CreateLoan.cs
> +                UserId =_userAccessor.GetCurrentUserID(),
o loan é feito por um client e nao por um appUser

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Features/Loans/UpdateLoan.cs
rever a nomenclatura da classe
esta classe apenas altera o status de um emprestimo

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Specifications/GetAllUser.cs
> +       // AddInclude(x=>x.);
deixar o codigo clean
nao podem haver comentarios de codigo

2023-03-17 00:28 UTC, FranciscoUqueio commented on Application/Specifications/GetAllUser.cs
qual é a necessidade deste specification?

2023-03-17 00:28 UTC, FranciscoUqueio commented on Domain/Purchase.cs
> +    public string UserId { get; set; }
quem compra é um cliente e nao um user

2023-03-17 00:28 UTC, FranciscoUqueio commented on Infrastructure/Services/ListOfAuthorsService.cs
> +    public List<BookAuthor> GetAuthors(int bookId)
se a informacao de Book nao é necessaria, porquê nao retornar apenas uma List<Author>?

2023-03-17 00:28 UTC, FranciscoUqueio commented on Persistence/SeedData/DbInitializer.cs
> +        if (!_context.Categories.Any())
criar uma List<Cateory> e adicionar os objectos a lista e depois inserir na bd utilizando o AddRange tem menos custos para na aplicacao

2023-03-27 11:06 UTC, xpntek requested changes

2023-03-27 11:06 UTC, xpntek commented on Application/Features/Authors/CreateAuthors.cs
> +                FullName = request.FullName.ToLower(),
porquê mandas o objecto com ToLower()?

2023-03-27 11:06 UTC, xpntek commented on Application/Features/Authors/Specifications/FoundAuthorByFullNameSpecification.cs
> +    public FoundAuthorByFullNameSpecification(string fullName) : base(author => author.FullName == fullName.ToLower())
por mais que tenhas gravado o objecto com ToLower() nada garante que os dados na BD sempre virao de como mandaste para a BD. Há possibilidade do dado ser alterado
Alguns SGBDs alteram o formato do objecto ao armazenar na BD

2023-03-27 11:06 UTC, xpntek commented on Application/Features/Books/CreateBookAuthor.cs
> +                    ISBN = request.ISBN.ToLower(),
o comentario anterior é válido para este caso

2023-03-27 11:06 UTC, xpntek commented on Application/Features/Books/ListBookAuthor.cs
rever nomenclatura da classe

2023-03-27 11:06 UTC, xpntek commented on Application/Features/Books/Specifications/FoundBookByISBNSpecification.cs
> +    public FoundBookByISBNSpecification(string ISBN):base(book => book.Book.ISBN==ISBN.ToLower())
um dos comentarios anteriores é valido para este caso

2023-03-27 11:06 UTC, xpntek commented on Application/Features/Categories/Specifications/FoundCategoryByDescriptionSpecification.cs
> +    public FoundCategoryByDescriptionSpecification( string description) : base(category =>category.Description== description.ToLower() )
um dos comentários anteriores é valido para este caso

2023-03-27 11:06 UTC, xpntek commented on Application/Features/Favorites/Specifications/ListFavoriteSpecification.cs
> +    public ListFavoriteSpecification( string id) :base( favorite => favorite.Client.ApplicationUser.Id==id)
nao existe uma forma de reduzir os saltos feitos?

2023-03-27 11:06 UTC, xpntek commented on Application/Features/Loans/CreateLoan.cs
> +                return Results.InternalError(" The user must make one loan ");
comentario ainda é valido

2023-03-27 11:06 UTC, xpntek commented on Application/Features/Loans/CreateLoan.cs
> +                EffectiveReturnDate = null
nao é aconselhavel criar um objecto com atributo com o valor null
se é opcional, nao se coloca na criacao do objecto

2023-03-27 11:06 UTC, xpntek commented on Application/Features/Loans/Specifications/GetLoanByUserIdSpecification.cs
> +    public GetLoanByUserIdSpecification( string userId) : base( loan =>loan.Client.ApplicationUser.Id==userId )
nao ha uma forma de reduzir os saltos?

2023-03-27 11:06 UTC, xpntek commented on Application/Features/Loans/UpdateEffectiveReturnDate.cs
> +        public DateTimeOffset? EffectiveReturnDate { get; set; }
porquê que o atributo é opcional?

2023-04-12 14:33 UTC, closed without merging